comment_width = 100
condense_wildcard_suffixes = true
edition = "2021"
empty_item_single_line = false
error_on_line_overflow = true
force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
